"""Read-only access to local evaluation artifacts generated by the evaluation harness."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, cast

from fastapi import APIRouter, HTTPException, status

router = APIRouter(prefix="/api/v1/evaluations", tags=["evaluations"])


@router.get("/latest")
def latest_evaluation() -> dict[str, Any]:
    """Return the newest generated evaluation report when one is available."""

    report_dir = Path("artifacts/evaluations")
    reports = sorted(report_dir.glob("*.json"), reverse=True)
    if not reports:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No evaluation report exists yet. Run `make evaluate` first.",
        )
    return cast(dict[str, Any], json.loads(reports[0].read_text(encoding="utf-8")))
